### ISSUE TITLE
When calling `parseLine` without an options param, an exception is thrown

### ISSUE THREAD

**Issue by mattbasta** [akhoury/ginx#12]
The docs indicate that the `options` param on `parseLine()` is optional. When you don't provide it, though, you get this error:

```
[GINX][ERROR][uncaughtException] TypeError: Cannot read property 'file' of undefined
[GINX-WARN] Exiting - No cursors were stored 
/opt/pinecast-softmirror/src/tailor/node_modules/ginx/lib/ginx.js:519
    throw err;
    ^

TypeError: Cannot read property 'file' of undefined
    at Ginx.eval [as hardParseLine] (eval at generateParseLine (/opt/pinecast-softmirror/src/tailor/node_modules/ginx/lib/ginx.js:347:19), <anonymous>:60:24)
    at Ginx.parseLine (/opt/pinecast-softmirror/src/tailor/node_modules/ginx/lib/ginx.js:182:10)
```

It seems like [this line](https://github.com/akhoury/ginx/blob/master/lib/ginx.js#L182) should be updated to something like this:

```js
this.hardParseLine(line, callback, options || {});
```

That said, I don't know for sure.

**Comment by akhoury** [comment]
i am not 100% sure how to reproduce the issue, but that should do it.

Anyways, didn't really know that anyone is still using this module, lol - it has been unmaintained for like 3 years

**Comment by mattbasta** [comment]
Thanks for the quick fix, man. I'm using ginx to parse some nginx access logs for a log aggregation service. I figured it'd be better to use it than rolling my own :)

A simple way to reproduce the issue is to just create a new Ginx object and call parseLine without an options param:

```js
var Ginx = require('ginx');
var g = new Ginx(null, {persistent: false});
g.parseLine('foo', function() {}); // no options param
```

The third line will throw the exception. The generated function code looks at `options.file`, which fails because `options` is undefined.
