### ISSUE TITLE
Does not work with my format

### ISSUE THREAD

**Issue by danielsitnik** [akhoury/ginx#15]
I use the standard nginx format with $request_time added at the end:
`$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time`

My log lines look like this:
`172.xx.xx.xx - - [23/Nov/2016:16:12:26 +0000] "GET /config/?platform=..... HTTP/1.1" 200 663 "-" "okhttp/2.3.0" 0.008`

Ginx parses the logs without errors, but the returned objects do not contain a request_time property with the 0.008 value.

I have uncommented line 346 in ginx.js to see the generated "funcode", and indeed it doesn't seem to have a section to parse $request_time. My guess is because I have no delimiters for this value like double quotes or a dash, so it's being ignored.

**Comment by akhoury** [comment]
oh man! didn't even think that anyone is using this old module. 
ok I think I fixed it

You are passing the format as a first argument when you create the Ginx object, right?

```javascript
  var parser = new Ginx('$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_time'});
```

update to [`ginx@0.0.5`](https://www.npmjs.com/package/ginx) and try `node demo.js` I updated the `./test/logs/nginx_prod-tiny.log` to match your case with the `$request_time` at the end

**Comment by danielsitnik** [comment]
@akhoury thanks, works beautifully now! 😄 

I know this is kinda old, but I found a reference for it while browsing the net for something to parse nginx files. I need to convert my logs to CSV while doing some transformations on the data and ginx seems to be the perfect tool for me.
